'use client'

import React from 'react'
import { BackgroundGradient } from './ui/background-gradient'

const modules = [
  {
    id: 1,
    title: 'Instant Document Summarization',
    slug: 'summarization',
    description:
      'Upload PDFs, DOCX, or TXT files and receive concise, meaningful summaries generated by AI.',
  },
  {
    id: 2,
    title: 'Key Point Extraction',
    slug: 'key-points',
    description:
      'Automatically extract bullet-point highlights and important facts from lengthy documents.',
  },
  {
    id: 3,
    title: 'Contextual Q&A',
    slug: 'qa',
    description:
      'Ask questions directly about your uploaded content and get relevant answers using LangChain + OpenAI.',
  },
]

function FeaturedModules() {
  return (
    <section className="py-20 bg-gray-900 text-white">
      <div className="text-center mb-12 px-4">
        <h2 className="text-teal-500 font-semibold text-sm tracking-widest uppercase">
          Featured Modules
        </h2>
        <p className="text-3xl sm:text-4xl font-bold mt-2">
          Empowering You To Read Smarter
        </p>
        <p className="text-neutral-400 mt-2 text-sm sm:text-base max-w-xl mx-auto">
          DocuScan AI delivers cutting-edge features to help users interact with and understand documents faster and smarter.
        </p>
      </div>

      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-10 px-6 max-w-7xl mx-auto">
        {modules.map((module) => (
          <div key={module.id} className="flex justify-center">
            <BackgroundGradient className="flex flex-col rounded-[22px] bg-white dark:bg-zinc-900 overflow-hidden max-w-sm w-full transition-transform hover:scale-[1.02]">
              <div className="p-6 text-center flex flex-col h-full">
                <h3 className="text-xl font-semibold text-black dark:text-white mb-2">
                  {module.title}
                </h3>
                <p className="text-neutral-600 dark:text-neutral-400 flex-grow">
                  {module.description}
                </p>
              </div>
            </BackgroundGradient>
          </div>
        ))}
      </div>

      
    </section>
  )
}

export default FeaturedModules
